<?php
namespace CakeContent\Controller\Admin;

use Cake\Event\Event;
use CakeContent\Controller\AbstractNodesController;
use CakeContent\Controller\AppController;

/**
 * Nodes Controller
 *
 * @property \CakeContent\Model\Table\NodesTable $Nodes
 */
class NodesController extends AbstractNodesController 
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->deny();
    }
}
