<?php
namespace CakeContent\Controller;

use CakeContent\Controller\AppController;
use CakeMarkdown\May\MeowDown;

/**
 * Nodes Controller
 *
 * @property \CakeContent\Model\Table\NodesTable $Nodes
 */
abstract class AbstractNodesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadComponent('CakeFile.Uploader', [
            'upload_domain' => 'nodes',
            'upload_dir' => 'images',
            'allowed' => ['png', 'jpg', 'jpeg', 'gif']
        ]);
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Users', 'Terms', 'ParentNodes']
        ];
        $nodes = $this->paginate($this->Nodes);

        $this->set(compact('nodes'));
        $this->set('_serialize', ['nodes']);
    }

    /**
     * View method
     *
     * @param string|null $id Node id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $node = $this->Nodes->get($id, [
            'contain' => ['Users', 'Terms', 'ParentNodes', 'Tags', 'ChildNodes']
        ]);

        $node->node_type ? $this->viewBuilder()->template($node->node_type . '_view') : '';

        // decode custom attributes from json string
        $node->CustomAttributes = json_decode($node->node_attributes);

        $MeowDown = new MeowDown();

        $node->markdown_body = $MeowDown->parse($node->body);

        $this->set('node', $node);
        $this->set('_serialize', ['node']);
    }

    /**
     * Add method
     *
     * @param $nodeType
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add($nodeType = null)
    {
        $node = $this->Nodes->newEntity();

        $nodeType ? $this->viewBuilder()->template($nodeType . '_add') : '';

        // is set any node type?
        $node->node_type = $nodeType;

        if ($this->request->is('post')) {
            $node = $this->Nodes->patchEntity($node, $this->request->data);
            $node->user_id = $this->Auth->user('id');

            //check if is uploaded any image
            if($node->image['size']) {
                $node->attribute_image = $this->Uploader->upload($node->image);
            }

            if ($this->Nodes->save($node)) {
                $this->Flash->success(__('The node has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The node could not be saved. Please, try again.'));
            }
        }
        $users = $this->Nodes->Users->find('list', ['limit' => 200]);
        $terms = $this->Nodes->Terms->find('list', ['limit' => 200]);
        $parentNodes = $this->Nodes->ParentNodes->find('list', ['limit' => 200]);
        $tags = $this->Nodes->Tags->find('list', ['limit' => 200]);
        $this->set(compact('node', 'users', 'terms', 'parentNodes', 'tags'));
        $this->set('_serialize', ['node']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Node id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $node = $this->Nodes->get($id, [
            'contain' => ['Tags']
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $node = $this->Nodes->patchEntity($node, $this->request->data);
            if ($this->Nodes->save($node)) {
                $this->Flash->success(__('The node has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The node could not be saved. Please, try again.'));
            }
        }
        $users = $this->Nodes->Users->find('list', ['limit' => 200]);
        $terms = $this->Nodes->Terms->find('list', ['limit' => 200]);
        $parentNodes = $this->Nodes->ParentNodes->find('list', ['limit' => 200]);
        $tags = $this->Nodes->Tags->find('list', ['limit' => 200]);
        $this->set(compact('node', 'users', 'terms', 'parentNodes', 'tags'));
        $this->set('_serialize', ['node']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Node id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $node = $this->Nodes->get($id);
        if ($this->Nodes->delete($node)) {
            $this->Flash->success(__('The node has been deleted.'));
        } else {
            $this->Flash->error(__('The node could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    /**
     * tags method
     */
    public function tags()
    {
        $tags = $this->request->params['pass'];

        $nodes = $this->Nodes->find('tagged', [
            'tags' => $tags
        ]);

        $this->set([
            'nodes' => $nodes,
            'tags' => $tags
        ]);
    }
}
