<?php
namespace CakeContent\Controller\Api;

use CakeContent\Controller\AbstractNodesController;

/**
 * Nodes Controller
 *
 * @property \CakeContent\Model\Table\NodesTable $Nodes
 */
class NodesController extends AbstractNodesController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub

        $paginate = $this->request->paging;

        $this->set(compact('nodes', 'paginate'));
        $this->set('_serialize', ['nodes', 'paginate']);
    }

    public function add()
    {
        $message = 'Not Implemented yet!';
        $this->set('message', $message);
        $this->set('_serialize', ['message']);
    }

    public function edit($id = null)
    {
        //return parent::edit($id); // TODO: Change the autogenerated stub
        $message = 'Not Implemented yet!';
        $this->set('message', $message);
        $this->set('_serialize', ['message']);
    }

    public function delete($id = null)
    {
        //return parent::delete($id); // TODO: Change the autogenerated stub
        $message = 'Not Implemented yet!';
        $this->set('message', $message);
        $this->set('_serialize', ['message']);
    }
}
